Repository googleapis/releasetool, pull requests merged in 2018-11, with the labels that each got.

#99 Add reporting commands for release builds
  releasetool/commands/publish_reporter.py
  releasetool/github.py
  releasetool/main.py
Labels: cla: yes

#100 Release releasetool 2018.11.01
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#102 Let reporter figure out the github token location instead of needing to manually specify it
  releasetool/commands/publish_reporter.py
Labels: cla: yes

#101 Add release reporter script.
  .kokoro/release.sh
  MANIFEST.in
  releasetool/__main__.py
  releasetool/commands/publish_reporter.py
  releasetool/commands/publish_reporter.sh
  setup.py
Labels: cla: yes

#106 Release releasetool 2018.11.02
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#107 Add github bot token to release build
  .kokoro/release.cfg
Labels: cla: yes

#108 Release releasetool 2018.11.02.1
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#109 Allow version regex to include more than 3 segments. Matches PEP440.
  releasetool/commands/tag/python.py
Labels: cla: yes

#114 Update github issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
Labels: cla: yes

#113 Fix release reporter's determination of the GitHub token
  releasetool/__main__.py
  releasetool/commands/publish_reporter.py
  releasetool/commands/publish_reporter.sh
Labels: cla: yes

#112 Prompt when a calver release collides with the most recent release tag.
  releasetool/commands/start/python_tool.py
Labels: cla: yes

#115 Install releasetool from source in the release job
  .kokoro/release.sh
Labels: cla: yes

#116 Release releasetool 2018.11.05
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#119 Add steps for tagging the merged commit for the release
  README.md
Labels: cla: yes

#118 Make tag idempotent
  releasetool/commands/common.py
  releasetool/commands/tag/java.py
  releasetool/commands/tag/nodejs.py
  releasetool/commands/tag/python.py
  releasetool/commands/tag/python_tool.py
  releasetool/commands/tag/ruby.py
  releasetool/github.py
Labels: cla: yes

#120 Use yoshi-automation GitHub account
  .kokoro/release.cfg
  releasetool/commands/publish_reporter.py
Labels: cla: yes

#121 Release releasetool 2018.11.07
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#122 Catch requests exceptions when checking if a release exists
  releasetool/commands/common.py
Labels: cla: yes

#123 Release releasetool 2018.11.07.1
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#125 Release releasetool 2018.11.07.2
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#126 Make nodejs releasetool tag work in non-interactive mode
  releasetool/commands/common.py
  releasetool/commands/tag/nodejs.py
  releasetool/commands/tag/python_tool.py
Labels: cla: yes

#128 Go commit msg
  releasetool/commands/start/go.py
Labels: cla: yes

#129 Make releasetool tag for Python work in non-interactive mode
  releasetool/commands/tag/python.py
Labels: cla: yes

#131 Don't try to commit samples/package.json if it doesn't exist
  releasetool/commands/start/nodejs.py
Labels: cla: yes
