Repository googleapis/releasetool, pull requests merged in 2018-10, with the labels that each got.

#67 start command for Go
  releasetool/commands/start/go.py
  releasetool/main.py
Labels: cla: yes

#75 fix(nodejs): change output from PyPI -> npm
  releasetool/commands/tag/nodejs.py
Labels: cla: yes

#73 Autodetect java if a root pom.xml file exists
  releasetool/main.py
Labels: cla: yes

#76 Cut release branch from master, warn when master != upstream/master.
  releasetool/commands/common.py
  releasetool/commands/start/python.py
  releasetool/git.py
Labels: cla: yes

#74 Java: support multiple versions per release
  releasetool/commands/start/java.py
Labels: cla: yes

#77 Release releasetool 0.10.0
  CHANGELOG.md
  setup.py
Labels: cla: yes

#79 Add command to reset GitHub API key
  .kokoro/build.sh
  README.md
  releasetool/main.py
  releasetool/secrets.py
Labels: cla: yes

#80 Use CalVer for Python Tools
  releasetool/commands/common.py
  releasetool/commands/start/go.py
  releasetool/commands/start/python_tool.py
  setup.py
Labels: cla: yes

#82 Release releasetool 2018.10.23
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending

#85 Allow python-tool tag to be executed with external context.
  releasetool/commands/start/go.py
  releasetool/commands/start/java.py
  releasetool/commands/start/nodejs.py
  releasetool/commands/start/python.py
  releasetool/commands/start/ruby.py
  releasetool/commands/tag/java.py
  releasetool/commands/tag/nodejs.py
  releasetool/commands/tag/python.py
  releasetool/commands/tag/python_tool.py
  releasetool/commands/tag/ruby.py
  releasetool/github.py
Labels: cla: yes

#86 Release releasetool 2018.10.25
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#87 Finish up autorelease support for python-tool
  releasetool/commands/common.py
  releasetool/commands/start/python.py
  releasetool/commands/tag/python.py
  releasetool/commands/tag/python_tool.py
  releasetool/github.py
Labels: cla: yes

#94 Only use calver for python_tools, not python
  releasetool/commands/start/python_tool.py
Labels: cla: yes

#91 Create tag context and move publish_via_kokoro to common
  releasetool/commands/common.py
  releasetool/commands/tag/java.py
  releasetool/commands/tag/nodejs.py
  releasetool/commands/tag/python.py
  releasetool/commands/tag/python_tool.py
  releasetool/commands/tag/ruby.py
Labels: cla: yes

#92 Allow remotes that don't end in .git
  releasetool/git.py
Labels: cla: yes

#97 Only apply autorelease tag for python-tool (for now).
  releasetool/commands/start/python.py
  releasetool/commands/start/python_tool.py
Labels: cla: yes

#98 Release releasetool 2018.10.31
  CHANGELOG.md
  setup.py
Labels: cla: yes, releasetool: pending
