Repository googleapis/releasetool, pull requests merged in 2019-05, with the labels that each got.

#178 Java: support updating dependencies.properties
  releasetool/commands/start/java.py
Labels: :rotating_light:, cla: yes

#184 Fix Ruby start#determine_last_release
  releasetool/commands/start/ruby.py
  tests/commands/start/test_ruby.py
Labels: cla: yes

#185 Release releasetool 2019.05.02
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#187 ruby: Add checkout_master() to finish of start
  releasetool/commands/start/ruby.py
  releasetool/git.py
Labels: cla: yes

#188 Update releasetool.commands.common.setup_github_context
  releasetool/commands/common.py
Labels: cla: yes

#186 ruby: Update start create_release_pr()
  releasetool/commands/start/ruby.py
  releasetool/git.py
Labels: cla: yes

#190 fix tagging for google-cloud package
  releasetool/commands/tag/ruby.py
Labels: cla: yes

#192 Fix changelog detection for Ruby.
  releasetool/commands/tag/ruby.py
Labels: cla: yes

#193 fix: release extraction regex was not handling patch releases properly
  releasetool/commands/tag/nodejs.py
  tests/commands/tag/test_nodejs.py
Labels: cla: yes

#166 DO NOT MERGE: Use magic github proxy for releasetool reporter
  .kokoro/release.cfg
  releasetool/commands/publish_reporter.py
  releasetool/github.py
Labels: :rotating_light:, cla: yes
